#!/bin/bash

set -e

# By default, analyze loops.c
SRC="loops.c"
if [[ $1 != "" ]]; then
    SRC=$1
fi

# FIX HERE
BUILD_DIR=""
if ! [[ -d ${BUILD_DIR} ]]; then
    echo "Set BUILD_DIR in this script to something meaningful" >&2 && exit -1
fi
LIB_DIR="${BUILD_DIR}/lib/LLVMMyLoopPass.so"

# Clang options
LL=${SRC%.c}.ll
LL_NORM=${SRC%.c}_norm.ll
PASSES="mem2reg,function(loop(indvars),loop-simplify,loop(rotate))"

clang -S -emit-llvm ${SRC}

opt -passes=${PASSES} ${LL} -S -o ${LL_NORM}

ninja -C ${BUILD_DIR}

opt -load ${LIB_DIR} --mylooppass ${LL_NORM}
